### ISSUE TITLE
Conflict in case of different versions of the same xsd included

### ISSUE THREAD

**Issue by arnaudlefebvre** [mfalaize/schema-fetcher#1]
Hi,

I think there is an issue when we use this tools for an XSD which as in its imports different version of the same xsd.

Example with  http://xml.sandre.eaufrance.fr/scenario/eaux_litto/1.1/sandre_sc_qeli.xsd

In result we have a file sandre_ref_tax.xsd which is used in its version 1 and 1.1 . A search on this filename in all result files show that some xsd refers to a missing file, some refers to file sandre_ref_tax.xsd with namespace version 1 and others also refers to sandre_ref_tax.xsd but for version 1.1

![capture](https://cloud.githubusercontent.com/assets/607301/26006186/c5625e46-373b-11e7-96ad-63c16b407d16.PNG)

1_sandre_ref_tax.xsd and 1.1_sandre_ref_tax.xsd does not exist

Any Ideas ?

**Comment by mfalaize** [comment]
Strange. I tested with that URL and it works well. I don't have 1.1_sandre_ref_tax.xsd but sandre_ref_tax.xsd instead and these files exist.

![image](https://cloud.githubusercontent.com/assets/4295695/26007046/33519130-373f-11e7-8076-79a6a03cbb7f.png)

PS : I wrote this script for another SANDRE scenario (EDILABO) and it worked for me :-D

**Comment by arnaudlefebvre** [comment]
Thank you for your reply :)

I'll have a check in debug next week to see what's going on. I'll tell you if I find something

**Comment by arnaudlefebvre** [comment]
I think the problem is in generateFileName(). For some reasons i don't understand, sandre_ref_tax.xsd is not found in cache and overwritten by the second version. 

What Jdk / Jre version do you use ?

Anyway, if i change filename generation using root of url it works well, but file names are... ugly :)

**Comment by mfalaize** [comment]
I tested with Jdk 1.7 and 1.8 (script does not work at all for 1.6-) and the result is the same. I have no idea what could happen to you sorry.

**Comment by arnaudlefebvre** [comment]
ok, it works if i changed root url, so I close this issue. Do you want the modified code of generateFileName?
